server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://47.107.171.232:3306/skeleton?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Root123!@#
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  # thymeleaf
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html

mybatis:
  type-aliases-package: cn.tellsea.skeleton.business.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    cn.tellsea.skeleton.business.mapper: debug
